pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'riya61018/gitops-java-app'
        DOCKER_CREDS = credentials('docker-hub-creds')
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git credentialsId: 'github-creds', url: 'https://github.com/Riya61018/gitops-devops-project.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh "docker build -t $DOCKER_IMAGE:v1 docker/"
                    // Or if Dockerfile is in repo root:
                    // sh "docker build -t $DOCKER_IMAGE:v1 ."
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    sh "echo $DOCKER_CREDS_PSW | docker login -u $DOCKER_CREDS_USR --password-stdin"
                    sh "docker push $DOCKER_IMAGE:v1"
                }
            }
        }
    }
}
